<?php

namespace OpenWines\WebAppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AppellationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppellationRepository extends EntityRepository
{
}
