<?php

namespace OpenWines\WebAppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\QueryBuilder;

/**
 * CepageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CepageRepository extends BaseRepository
{
    /**
     * used in DQL expressions
     */
    const QUERY_ALIAS = 'c';


    /** ************* */
    /** F I N D E R S */

    public function findByAOCOrderByName($AOCId)
    {
        $query = $this->getEntityManager()
            ->createQuery('
            SELECT c, a FROM OpenWinesWebAppBundle:AOC a
            INNER JOIN a.AOC a
            WHERE a.id = :id'
            )->setParameter('id', (int)$AOCId);
        try {
            return $query->getSingleResult();
        } catch (NoResultException $e) {
            return null;
        }
    }

    /** *************** */
    /** B U I L D E R S */

}
