#%RAML 0.8
title: OpenWines API
version: v1
baseUri: http://openwines.web-app.io
mediaType: application/json
documentation:
 - title: OpenWines API
   content: !include documentation.md
schemas: !include schemas.raml
resourceTypes: !include resourceTypes.raml
traits: !include traits.raml
/vineyards:
  type: { collection: { example: !include examples/vineyard.raml } }
  /{id}:
    type: { item: { example: !include examples/vineyard.raml } }