# Schemas
- vineyard: |
    {
      "type": "object",
      "$schema": "http://json-schema.org/draft-03/schema",
      "documentation": "http://schema.org/AdministrativeArea",
      "id": "http://jsonschema.net",
      "required": true,
      "properties": {
        "name": {
          "type": "string",
          "required": true
        }
      }
    }
  
