# Traits
- paged:
    queryParameters:
      offset:
        description: number of rows to be skipped before starting to count the limited number of rows to be returned
      limit:
        description: number of rows to be returned
        type: number
- formatted:
    description: have a default formatted output
