<?php
/**
 * This file has been automaticaly generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */
namespace OpenWines\AppBundle\Db\OpenwinesSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Appellation
 *
 * Structure class for relation openwines.appellation.
 * hectares
 *
 * area:
 * hectares
 * production:
 * hectoliters
 * soil:
 * soil types
 *
 * @see RowStructure
 */
class Appellation extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     * @return null
     */
    public function __construct()
    {
        $this
            ->setRelation('openwines.appellation')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('vignoble_id', 'int4')
            ->addField('appelation_type', 'varchar')
            ->addField('name', 'varchar')
            ->addField('area', 'int4')
            ->addField('production', 'int4')
            ->addField('soil', 'varchar[]')
            ->addField('wine_type', 'varchar[]')
            ->addField('description', 'text')
            ->addField('more', 'text')
            ->addField('created_at', 'timestamptz')
            ->addField('updated_at', 'timestamptz')
            ;
    }
}
