<?php
/**
 * This file has been automaticaly generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */
namespace OpenWines\AppBundle\Db\OpenwinesSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Vignoble
 *
 * Structure class for relation openwines.vignoble.
 * hectares
 *
 * area:
 * hectares
 *
 * @see RowStructure
 */
class Vignoble extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     * @return null
     */
    public function __construct()
    {
        $this
            ->setRelation('openwines.vignoble')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('name', 'varchar')
            ->addField('description', 'text')
            ->addField('departments', 'int4[]')
            ->addField('area', 'int4')
            ->addField('more', 'text')
            ->addField('created_at', 'timestamptz')
            ->addField('updated_at', 'timestamptz')
            ;
    }
}
